### ISSUE TITLE
display of the map

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#101]
Hello, little problem with the display of the map on Sonde Hub, this has been done for a few days for me, it does so depending on the zoom used, never done before, thank you

![carte 1](https://user-images.githubusercontent.com/87615097/129451098-77b0fe76-5b24-4887-a4c9-7dcee078c2c3.JPG)
![CARTE 2](https://user-images.githubusercontent.com/87615097/129451099-8ee51745-620b-43ec-9d94-455a58164d55.JPG)

from my phone it's the same

![Screenshot_20210814-173947_Chrome](https://user-images.githubusercontent.com/87615097/129451599-9ac94e45-af7e-4627-b2ec-137038138cc3.jpg)

**Comment by LukePrior** [comment]
I'm not too sure what is causing this but the fact that it happens on SondeHub and SondeHub/card which both have different codebases makes me believe it is a problem with the shared osm mapserver.

**Comment by darksidelemm** [comment]
Yes, this is definitely a tileserver issue, not something that we can control.

**Comment by 14ri004** [comment]
hello and thank you for your answers, it's not very serious, it only partially, not really very annoying, thank you
