### ISSUE TITLE
probe frequency

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#102]
little question, I have a problem when I look at SondeHub on my phone (only), I do not display the frequency of the probe, this is a little annoying for the detected / tracked, Example: the Brest probe is on 404 Mhz and sometimes 403 Mhz.

![Screenshot_20210814-174443_Chrome](https://user-images.githubusercontent.com/87615097/129451961-1ceb249f-f238-4392-9db9-1d7c4984e9a2.jpg)

in the google settings of my phone, if I put the display in (computer version) I have the Frequency, but the display is ridiculously small

![Screenshot_20210814-175615_Chrome](https://user-images.githubusercontent.com/87615097/129452150-7c44ce88-92ce-4c1b-b7ce-0dcb955177b2.jpg)

**Comment by HoshenKadosh** [comment]
From what I have seen, you can:

1. Click on any point on the balloon path, a card will open which will show the full telemetry details at that point in the path, as well as the frequency of the sonde.
![Screenshot_20210815-024648.jpg](https://user-images.githubusercontent.com/47646557/129462833-f635e243-92b3-4274-adb5-bfb2c99a3647.jpg)

2. Tilt the phone horizontally, this will show the full telemetry sidebar.
![Screenshot_20210815-024719.jpg](https://user-images.githubusercontent.com/47646557/129462858-d5d7677d-5dee-4d95-9898-1a5c5ba22f7f.jpg)

**Comment by LukePrior** [comment]
Hi @14ri004,

We have limited display space on mobile so had to sacrifice most of the fields. The two options described by @HoshenKadosh are the only implementations we intend to offer currently.
