### ISSUE TITLE
atmospheric pressure

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#103]
hello, would it be possible to have the atmospheric pressure on the dashboard of SondeHub?, that would seem useful to me, if however it remains achievable, thank you

**Comment by darksidelemm** [comment]
Not sure what you mean by dashboard here, but radiosondes that we support decoding atmospheric pressure from (currently only the RS41-SGP) will show in the telemetry area.

**Comment by 14ri004** [comment]
hello, in this part of the software,

![HAB](https://user-images.githubusercontent.com/87615097/129690029-26bd3b17-3473-46e0-ac26-c90d961d451c.JPG)

**Comment by darksidelemm** [comment]
Yes, the RS41-SG radiosonde model does not have a pressure sensor! Only the RS41-SGP does.

**Comment by LukePrior** [comment]
![image](https://user-images.githubusercontent.com/22492406/129697500-3b8b56ff-9ca0-4a18-974e-097678fab4d2.png)

**Comment by rs1729** [comment]
should be 54.86 hPa.

**Comment by LukePrior** [comment]
> should be 54.86 hPa.

Thanks for catching that will update shortly
