### ISSUE TITLE
bug sondehub

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#128]
Hello, it's been several times since I noticed that the little blue man is not always visible on probehub, I use FIREFOX, this is not a problem, but I just wanted to warn you of this little bug, thank you

![A](https://user-images.githubusercontent.com/87615097/131327696-45371e19-51a5-4c1a-a64c-2ef061f47a02.JPG)
![B](https://user-images.githubusercontent.com/87615097/131327708-67b4ba50-b381-4ebf-8d53-a28a3390ddf2.JPG)

**Comment by darksidelemm** [comment]
This sounds like your browser isn't always able to provide your location. This isn't really something we can solve - it's dependent on your browser.

**Comment by 14ri004** [comment]
hello and thank you for your answer, I am using FIREFOX, my position is displayed at the top in the blue bar of SondeHub and it works when I click on it, it is just that the little guy is displayed 1 of 2 times, it's not a big deal, it's just to let you know, have a nice day
