### ISSUE TITLE
strange behavior of predictions

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#129]
![sonde etrange](https://user-images.githubusercontent.com/87615097/131419912-6a7d42b3-96c2-4078-911f-e9d7115fc9c7.JPG)

![sonde etrange2](https://user-images.githubusercontent.com/87615097/131420140-4e83cac3-9dc9-4f37-a1c6-47339bdb6bdc.JPG)

**Comment by LukePrior** [comment]
This is an rdzTTGOsonde issue.
