### ISSUE TITLE
M10 probe installation point

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#139]
on the M10 probes in France, the drop point is no longer visible, for the RS41 they are clearly visible, but no longer for the M10, see screenshots

![Screenshot_20210913-141028_Chrome](https://user-images.githubusercontent.com/87615097/133141974-c050dbef-b6e1-4a0e-a5d8-e8f5d73d667e.jpg)
![Screenshot_20210913-142336_Chrome](https://user-images.githubusercontent.com/87615097/133141989-418ed3f1-8083-4cbb-9281-575754aacf40.jpg)

**Comment by TheSkorm** [comment]
Sorry about this. Looks like the new prediction code was missing radiosondes that don't have a "sub type" This should be fixed now for new launches
