### ISSUE TITLE
Weather station in Kaliningrad, balloon start 11:30 and 23:30  UTC

### ISSUE THREAD

**Issue by ra2fgg** [projecthorus/sondehub-tracker#163]
Weather station in Kaliningrad, balloon start 11:30 and 23:30  UTC

**Comment by darksidelemm** [comment]
20m/s descent rate seems a bit fast? Is this the ground-level descent rate (which we need for the predictor)

**Comment by LukePrior** [comment]
I'm going to leave this with its current values for the time being.
