### ISSUE TITLE
MRZ-N1

### ISSUE THREAD

**Issue by BatiaMahno** [projecthorus/sondehub-tracker#172]
Hello, I am a hunter from Russia. The predictions for my probe at https://sondehub.org/ are very imprecise. We do not have a parachute, so the speed of the fall is 25 meters per second. The height of the balloon burst is 32 km. Please correct.

**Comment by darksidelemm** [comment]
I think I asked this somewhere else, but is this 25m/s value the speed *on landing*, or just at some point during descent?
(Also... that seems kind of dangerous, no matter how light the sonde might be!)

We also need information on the launch site that these launches are associated with to be able to correct this information.

**Comment by BatiaMahno** [comment]
The speed of the fall, measured during the fall, by the RMeteo program, is about 25 m / s. Launch site Belogorsk Crimea Russia 45.0448 /34.5980

**Comment by BatiaMahno** [comment]
The program is tied to SDR, this device is not of high quality, please modify the program for the option of connecting a better receiver via a sound card.

**Comment by darksidelemm** [comment]
Taking audio input from a sound card is not something that will ever be supported by auto_rx, sorry. 
The performance of a device like a RTLSDR is more than sufficient if you put a suitable preamp and filter in front of it. My stations have been able to receive radiosonde telemetry from >500km away without issue.
