### ISSUE TITLE
Ascent rates go to infinity / -infinity during flight

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#181]
We are seeing the ascent rate calculation ingest some bad number, such that the running calculation of ascent rate ends up at infinity. This is due to the 'infinite impulse response' averaging/filtering used at the moment, occurring here: https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L2727

A few approaches to fixing this:
- Detect if the result of a calculation results in an invalid result (e.g +/- inf), and discard it.
- Calculate the ascent rate over a fixed time window, so any bad values will shuffle out of the window eventually.

Detecting the +/- inf values is probably the better solution.

**Comment by darksidelemm** [comment]
Also... I'm thinking this line needs an isFinite check: https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L2734
That might fix the issue entirely.

**Comment by LukePrior** [comment]
I've added this to testing: https://github.com/projecthorus/sondehub-tracker/commit/de4c2f365cf29a5cd05a69c9b06f3d82f0c06d23.

If it all works ok will merge to main.
