### ISSUE TITLE
Lookup old launches from S3

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#182]
There's been a few requests now to be able to find information from old launches. We keep this data stored in S3 at https://sondehub-history.s3.amazonaws.com/index.html#launchsites/ , indexed per launch site, then year, month and day. 
We only have data going back to when we started performing reverse predictions unfortunately (October 10th 2021), so there may be a task ahead to go through the other archive (just year/month/day) and try and assign them to launch sites (as has been done using just the first position in https://github.com/projecthorus/sondehub-analysis )

As an example - https://sondehub-history.s3.amazonaws.com/launchsites/72649/2021/12/10/7424379.json 
Each json file contains a list, with three entries. These entries are a telemetry snapshot at the first-observed position, the burst position, and the last observed position. 

```
[{"software_name": "radiosonde_auto_rx", "software_version": "1.5.6", "uploader_callsign": "N0TOR", "uploader_position": "44.92332,-93.31888", "uploader_antenna": "1/4 wave monopole", "time_received": "2021-12-10T11:25:06.433229Z", "datetime": "2021-12-10T11:25:22.996000Z", "manufacturer": "Lockheed Martin", "type": "LMS6-1680", "serial": "7424379", "frame": 2822, "lat": 44.89255, "lon": -93.30655, "alt": 6732.738, "vel_v": 4.774, "vel_h": 41.06347, "heading": 67.18597, "frequency": 1676.03, "user-agent": "Amazon CloudFront", "position": "44.89255,-93.30655", "upload_time_delta": -0.593, "uploader_alt": 274.0, "launch_site": "72649", "launch_site_range_estimate": 6261.784657248283}, {"software_name": "radiosonde_auto_rx", "software_version": "1.5.7", "uploader_callsign": "KV0KEV", "uploader_position": "45.155261333,-93.058856833", "uploader_antenna": "Nooelec 1100-1800 MHz helical + 1688 MHz LNA", "time_received": "2021-12-10T12:45:46.606525Z", "datetime": "2021-12-10T12:46:02.995000Z", "manufacturer": "Lockheed Martin", "type": "LMS6-1680", "serial": "7424379", "frame": 7662, "lat": 44.86772, "lon": -91.72599, "alt": 32318.834, "vel_v": 2.448, "vel_h": 17.9355, "heading": 195.33413, "frequency": 1676.06, "user-agent": "Amazon CloudFront", "position": "44.86772,-91.72599", "upload_time_delta": -1.293, "uploader_alt": 288.8, "launch_site": "72649", "launch_site_range_estimate": 6261.784657248283}, {"software_name": "radiosonde_auto_rx", "software_version": "1.5.7", "uploader_callsign": "KV0KEV", "uploader_position": "45.155350025,-93.058905945", "uploader_antenna": "Nooelec 1100-1800 MHz helical + 1688 MHz LNA", "time_received": "2021-12-10T13:17:37.475261Z", "datetime": "2021-12-10T13:17:53.995000Z", "manufacturer": "Lockheed Martin", "type": "LMS6-1680", "serial": "7424379", "frame": 9573, "lat": 44.87669, "lon": -91.03703, "alt": 10432.6, "vel_v": -5.288, "vel_h": 65.64823, "heading": 78.10262, "frequency": 1676.06, "user-agent": "Amazon CloudFront", "position": "44.87669,-91.03703", "upload_time_delta": -0.939, "uploader_alt": 303.992, "launch_site": "72649", "launch_site_range_estimate": 6261.784657248283}]
```

What would be ideal, is for the user to be able to click on a launch site, select a year and month, and click something which then goes and queries for sondes in that range, and then adds the last received position for each sonde on the map. 

This should also make use of the recovered sondes API (https://api.v2.sondehub.org/recovered?serial=<serial>) to indicate if the sonde was marked as recovered or not. 
Data that should appear in the popup for each landed sonde should be:
- Last altitude
- Last receiver (uploader_callsign)
- Recovery information
- Button to download and show the rest of the flight path.
- Button to link off to sondehub.org/card to get a SkewT plot. 
- (Can we get the last prediction for a sonde out of ES?)

I would suggest using the coloured icons for sondes that have no recovery information, and the grey (uncrossed and crossed) icons for the ones with recovery information (recovered or not recovered). 

The user should be able to continue to select more months/years and grab more data to show on the map. I figure doing the lookups month-by-month will keep what ends up on the map somewhat under control. We would also need a clear button to clear all the markers away. 

Tim McMahon has provided some example code for querying S3 data from javascript here: https://gist.github.com/TimMcMahon/546a6868a375a15828abc4d3df4f602c#file-listlaunchsitefilesforsonde-html

**Comment by LukePrior** [comment]
See https://github.com/projecthorus/sondehub-tracker/pull/198 for an initial version.

**Comment by LukePrior** [comment]
This is now live.
