### ISSUE TITLE
Sodankylä prediction delete leave allways one path

### ISSUE THREAD

**Issue by oh3bsg** [projecthorus/sondehub-tracker#193]
When generate prediction from Sodankylä station (ID: 02836) and then  delete those path using delete button, then allways one path will not deleted.
This happens only sodankylä station.

**Comment by LukePrior** [comment]
That is strange, I can confirm I'm also experiencing the error and will investigate further.

**Comment by LukePrior** [comment]
The issue was that Everyday at 12:00 UTC & Wednesday at 12:00 UTC were both creating markers but only one was getting deleted. I've ensured that every prediction needs to have a unique value and this has solved the problem. The fix should be live on the site in a few minutes.

**Comment by LukePrior** [comment]
https://github.com/projecthorus/sondehub-tracker/pull/195
