### ISSUE TITLE
Skew-T Plot

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#2]
It would be cool to be able to select a sonde, then open a Skew-T plot for the sonde flight, kind of like how we can open up a telemetry graph.

An functional Skew-T plotting library is here: https://github.com/dfelix/skewt-js
At the moment this library does a single skew-t plot. 

- Check how the telemetry graph data is stored. For a skew-t plot we will need a history of wind speed and direction, which i think is not currently stored. The other option is that when the skew-T plot is opened, we request the backlog data for the sonde we are interested in, and then calculate it then.  
- Have a button (like the telemetry graph button), which slides open a pane, perhaps to the right of the screen.
- Plot the SkewT in that pane.

**Comment by darksidelemm** [comment]
This may be a better fork to work with: https://github.com/rittels/skewt-js

**Comment by LukePrior** [comment]
initial version in testing,

**Comment by LukePrior** [comment]
This all seems to be working.
