### ISSUE TITLE
https://sondehub.org : Launchtime Uccle, Belgium

### ISSUE THREAD

**Issue by dg7vm** [projecthorus/sondehub-tracker#230]
Hi all, 

Uccle launchtime is   11:30z   (Mon, Wed, Fri) .

Source (pse read on page 10) :
https://ozone.meteo.be/uploads/media/5fd8f51c93852/uccle-presto-debacker1999.pdf?token=/uploads/media/5fd8f51c93852/uccle-presto-debacker1999.pdf

vy 73
Norbert, DG7VM

**Comment by LukePrior** [comment]
Is that information accurate the document is 23 years old?

If so please use this Google Form to submit this and future suggestions: https://forms.gle/GserZmFAif5z9QXH9

They will appear in the pinned issue: https://github.com/projecthorus/sondehub-tracker/issues/114

Thanks
