### ISSUE TITLE
Sonde Alert

### ISSUE THREAD

**Issue by pcapovilla** [projecthorus/sondehub-tracker#231]
When the landing forecast is at "X" distance from the mobile phone with the application, it sends an alert of an upcoming fall

**Comment by darksidelemm** [comment]
Given the predictions are only run on demand, when you click the 'generate predictions' button, I'm not entirely sure how you are expecting this to work?

What you're asking is more of a back-end service feature than something that belongs in the tracker itself.

**Comment by LukePrior** [comment]
Yeah this isn't something that is going to be added to the tracker. You should be able to create a simple script using the data available from the SondeHub API and checking how we generate predictions for your specific launch site in chrome Dev tools.
