### ISSUE TITLE
probe colors

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#238]
hello, I would like to know what the colors of the probes correspond to in the history, what is the use of the colors??, thank you
![sondes](https://user-images.githubusercontent.com/87615097/152863037-1b1420e8-b795-45fc-9dd5-85e0d97bc2f5.JPG)

**Comment by LukePrior** [comment]
They correlate to the last detected altitude.

See: https://github.com/projecthorus/sondehub-tracker/wiki/SondeHub-Tracker-User-Guide#historical-launch-site-data

**Comment by 14ri004** [comment]
thank you
