### ISSUE TITLE
ascent / descent rate when clicking anywhere on the track ?

### ISSUE THREAD

**Issue by zanco** [projecthorus/sondehub-tracker#239]
Hi, would it be possible to show the burst, and in relation to that, ascent and descent rate when clicking on a point on a track ?

![image](https://user-images.githubusercontent.com/4477734/153654357-c00a3f86-e83e-4816-9d61-418ea4224ade.png)

Thanks,

Ben

**Comment by LukePrior** [comment]
Hi Ben,

I've had a bit of a look into this but the way it works makes it quite difficult to implement as these values are all calculated from an entire sonde data set but for the card we query an individual frame where these cannot always be accurately determined, I will keep it in mind if I ever do a rework of the system.

Thanks,
Luke
