### ISSUE TITLE
Optionally Disabling Auto-Zoom on Click?

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-tracker#240]
Hi,

In some cases, the auto-zoom feature upon clicking a sonde is not that convenient, for example - when exploring large areas on the map.
Maybe we can have a configuration option to turn it off? Or maybe disabling it some other way...? (e.g., no zoom on double-click)
 
Thanks.

**Comment by LukePrior** [comment]
I don't personally plan to implement such a feature but I would consider a well-implemented PR.
