### ISSUE TITLE
zoom sondehub

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#242]
Hello, would it be possible to put an elevator instead of the + and - for the Zoom, it would be faster than clicking 5 or 6 times to change the zoom of the map, thank you

![sondehub](https://user-images.githubusercontent.com/87615097/154786745-261b6a4e-a676-439f-8172-44e0e83dd36f.JPG)

**Comment by LukePrior** [comment]
I don't personally plan to implement such a feature but I would consider a well-implemented PR.
