### ISSUE TITLE
Some chase cars icons not showing

### ISSUE THREAD

**Issue by HoshenKadosh** [projecthorus/sondehub-tracker#244]
Hi,  sometimes I can see that chase cars are not showing up with the icon on the map, instead - only the callsign is shown.
Altho the chase car in the image is not mine, I have encountered the issues while chasing a sonde recently. 

Thanks.

![image](https://user-images.githubusercontent.com/47646557/157155885-2881dca4-928a-4798-b077-f57c32e07bc8.png)

**Comment by darksidelemm** [comment]
I can confirm I've seen this before. It didn't seem to be easy to replicate, but good to know others have seen it.

**Comment by LukePrior** [comment]
I have now added this to main, please re-open if the issue persists.
