### ISSUE TITLE
Data from database into skewt

### ISSUE THREAD

**Issue by weather01089** [projecthorus/sondehub-tracker#250]
Hi, I am creating a local comma deliminated file to feed into the SHARP sounding program. 

The data being stored, and forwarded to the sondehub database has some false winds at low levels.
Somehow the skewt on the site is correct.

Can you tell me how you are parsing that database data to create that skew-t?

Thanks!

Ray Weber

**Comment by darksidelemm** [comment]
Can you give an example of the bad data vs what's on the sondehub skewt?

It's worth noting that we calculate wind based on deltas between positions, not based on individual telemetry data. 

The code that goes through the telemetry for a particular sonde on the tracker is here: https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L1809

**Comment by weather01089** [comment]
ahh OK, the RS41 is what was used, and it reports the wind direction. Thats what we were using

the sonde was T4840488 from louisiana, US.

it was on 03/22/2022

attached is a created pysharpfile  of the data. It matches the sondehub database.

I do note if you use the lat/lon delta, it does appear to be the right direction. Not sure why the sonde reports it incorrectly.

Ill see if I can duplicate what you do in your code, as its correct.

Ray
________________________________
