### ISSUE TITLE
Lack of Helium causes smaller Balloons and lower maximal height!

### ISSUE THREAD

**Issue by Dl5RCB** [projecthorus/sondehub-tracker#251]
Balloons started at Kümmersbruck in the last days only reach a height of about 20000m. The launchteam uses smaller balloons and less Helium. The team told me the other launchpoints will follow. Therefore the heights for the predictions shoud be adjusted !

**Comment by LukePrior** [comment]
Hi @Dl5RCB,

I have updated the Kümmersbruck launch site (10771) however please use the launch site modification form in the future when the other sites switch over.

![image](https://user-images.githubusercontent.com/22492406/160355927-6491b959-0c5a-4bf6-9b53-069afd823df2.png)

Thanks,
Luke
