### ISSUE TITLE
unable to report recovery without location services

### ISSUE THREAD

**Issue by drewarnett** [projecthorus/sondehub-tracker#260]
I recovered T4820142 and wanted to report recover (with notes).  Would be great if could report recovery without location services.  (No location services available on reporting device or no desire to not always use location services with the sondehub.org tracker.)  I tried reporting, but get  "Report Result Outside distance limit."

Perhaps for let's call it data quality issues, you don't want to allow this.  If not, please add to the docs the requirements for this feature to work.

On the data quality front, not clear to me how the recovery location is marked:  location of the chaser or last location received for the sonde.  Is it automagically determined, or is it explicit?

Thanks for the help!

**Comment by LukePrior** [comment]
You can also call the API directly bypassing the location requirement.

**Comment by drewarnett** [comment]
I clicked on the sonde icon.  I figured that's how it would decide to use
that coordinate instead of car.  But the check for 200 km is based on the
browser location, not the sonde last recorded location in that case?  Do I
understand correctly?

Meanwhile, looking at the API right now and will see if I can try that.
(Looks simple.  No questions so far.)
