### ISSUE TITLE
probes from a boat

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#261]
hello, how to find probes sent from a boat??, do you have a solution to this problem, thank you

**Comment by darksidelemm** [comment]
Not easily, no. 
If launch site is known (e.g. appears on the map), then we assign radiosondes to it if we determine they launched from that site (based on first observed positions, and reverse predictions), and then you can click on that site to get historical launches.

However, if a launch site is not known, or is not in a fixed place, then we do not assign the radiosonde to any site. Currently there is no lookup for unassigned sondes.

If a sonde appears on the map, you can zoom in and look at the reverse prediction to see where we estimate it may have been launched from.

**Comment by 14ri004** [comment]
hello, thank you for the answer it is what it seems to me, too bad for the probes to be released from the boats, cdt
