### ISSUE TITLE
redirection of predictor coordinates to the path to google maps

### ISSUE THREAD

**Issue by Aniolg75** [projecthorus/sondehub-tracker#262]
Hello
 I use SondeHUB tracker to catch weather probes. I miss one function such that by clicking on the landing probe predictor, I redirected me to google maps which sets the route. Currently, only predictor coordinates are listed there. This would make it easier to access the predictor before the probe lands
 Yours sincerely, Piotr SQ6NEI

**Comment by darksidelemm** [comment]
<img width="549" alt="Screen Shot 2022-10-03 at 16 04 45" src="https://user-images.githubusercontent.com/1040275/193507763-f429c59a-ca29-445f-8269-f868a9e9ecd1.png">
This should now be active on both sondehub and sondehub-amateur trackers. 
I'm using a 'geo' link, which will work on mobile devices, but will probably not work on desktop web browsers.
