### ISSUE TITLE
Upload to Sondehub from sondemonitor bug

### ISSUE THREAD

**Issue by lelun** [projecthorus/sondehub-tracker#264]
Hi i have been trying to upload to sondehub from my laptop via sondemonitor. the issue is that my station will show up on the map but the data that i am trying to send to sonde hub from sondemonitor seams to not work.

some information about setup the settup i am using is a RTL SDR reciver with Sdrsharp that is sending a audio input to sondemonitor. from there i am using the M10 decoder with a 45 bitrate to extract the data from the sondes used in my area Ørlandet norway, they use M20 sondes 

so my station shows up lelun/ lelun SDR but the baloon marker and other infomation dont. are you guys able to tell me if its sonde hub that are having issues or my sondemonitor? i am able to see cordinates and that in sonde monitor but not on sondehub.

**Comment by LukePrior** [comment]
I believe Sondemonitor only supports uploading RS41 data to SondeHub at this time.

**Comment by lelun** [comment]
alright i will try to contact the devs of sondemonitor and ask if they can look in to the ability to upload gps data from the M20 to Sondehub.

its a shame its not already implemented. i am tracking one right now that would be nice to see on sondehub.

**Comment by LukePrior** [comment]
I just had a look at the Sondemonitor version logs and it appears SondeHub uploading support has been extended to MeteoModem and Graw radiosondes in versions 6.2.6.2 and 6.2.6.7 so if you are running one of those versions or higher it should work in theory.

**Comment by LukePrior** [comment]
I checked the SondeHub database and haven't actually seen any non-RS41 sondes from SondeMonitor in the last 2 weeks so I'm not sure if this has been tested in reality.

**Comment by darksidelemm** [comment]
It hasn't been tested, and there are multiple issues that need to be
resolved with both M20 and DFM uploading before it will work.

**Comment by 14ri004** [comment]
probemonitor only supports RS41 and DFM at the moment version 6267

**Comment by darksidelemm** [comment]
DFM support is also not working. There are a number of issues with the uploaded telemetry which results in the telemetry being dropped by SondeHub. I've reported these issues to Bev.

**Comment by darksidelemm** [comment]
I'm going to close this issue, as this is not a SondeHub issue. This is a SondeMonitor issue, and you should be taking it up with Bev.

**Comment by lelun** [comment]
alright ill take it up with them.
thanks for the responce and hopefully they can get sondemonitor to upload the M20 data to sondehub. i decided to post here sence i was not sure where the issue was and decided to start on this end.
i am looking forward to upload the data from my region so the comunity can use it :)

again thanks for the help and i wish you guys a good day!
