### ISSUE TITLE
Filter "Hide receivers from the map" doesn't work without complete refresh of page

### ISSUE THREAD

**Issue by Torrehoradada** [projecthorus/sondehub-tracker#267]
Since last update the filter seems to be working differently:
Setting the filter does not remove the receiver marks (as how it was working before). You have to reload the complete page (not only the cached data) to remove those green dots.
Removing the filter does work instantly.
Actual running version is Tracker Revision: 78ca722
Build Date: 2022-10-07T23:59:34Z
Using Firefox under Linux Mint:
mint-001 - 1.0
Revision 105.0.1 (64-Bit)

Same behaviour can be observed with Firefox under Android and with Chrome.

PS: After having the tracker page open for some time, more and more receiver marks are reappearing again. The filter setting ist still on "Hide receivers..."
The same behavour is equal wether on "https://www.sondehub.org/" or on "https://tracker.sondehub.org/"

**Comment by darksidelemm** [comment]
Thanks for the report, this is likely due to some recent changes relating to how we handle receiver position updates.
Will look into it...

**Comment by darksidelemm** [comment]
Found the issue, will get a fix out today.

**Comment by darksidelemm** [comment]
This has been applied to the sondehub tracker, still need to make the changes on sondehub-amateur

**Comment by darksidelemm** [comment]
These change have now been applied on both Sondehub and Sondehub-Amateur. Let me know if you still have any issues.

**Comment by Torrehoradada** [comment]
Appeares to work without any hassle now. Thank you very much for the response and the quick debug!
