### ISSUE TITLE
Burst and Landing Icons don't completely convert to imperial units.

### ISSUE THREAD

**Issue by smad333** [projecthorus/sondehub-tracker#271]
As per title, burst and landing locations cannot be clicked for more information when in Imperial units mode only. Works fine if swapped back to metric units. Tried in Chrome, Explorer and Edge same result

**Comment by darksidelemm** [comment]
Should be fixed now :-)

Clearly I don't test the imperial unit setting enough...

**Comment by smad333** [comment]
Many thanks, this now works, although the units are still metric on the popup box

**Comment by smad333** [comment]
![image](https://user-images.githubusercontent.com/119420794/205029230-85fb0010-09a6-4af5-939b-bed8f7cbbb72.png)

**Comment by smad333** [comment]
Altitude is correct but not ascent, burst or descent

**Comment by darksidelemm** [comment]
Oh. Yes we don't convert those at the moment...

**Comment by TheSkorm** [comment]
Should be fixed on https://testing.v2.sondehub.org - can you confirm that the units are right?

**Comment by smad333** [comment]
I have just checked and it looks like the units are correct with every
combination of options. Well done and thank-you.
Adam
