### ISSUE TITLE
SkewT plot hanging in some cases

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#272]
Test case: http://tracker.sondehub.org/?sondehub=1#!mt=Mapnik&mz=11&qm=3h&f=U3014499&q=U3014499
Let this sonde path load, then try and plot a skewT.
It will just spin indefinitely, and the page will lock up.

If i put a console.log in before this line https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L1925
and here: https://github.com/projecthorus/sondehub-tracker/blob/master/js/skewt.js#L1290
I only get the first log entry (before the call to skewt.plot).
Unsure what is going on here :/

**Comment by TheSkorm** [comment]
This is probably because of bad data. This sensor stalk was broken. Sometimes humdity was reported as null

Tweaked the checks and how the data is formatted and it appears to have fixed it

```
20509.2395	-252.5	null
20509.2395	-252.5	100
20509.2395	-252.5	null
20509.2395	-252.5	100
20519.43467	-252.5	100
20519.43467	-252.5	100
20519.43467	-252.5	null
20519.43467	-252.5	null
20524.49467	-252.5	null
20524.49467	-252.5	null
20530.90419	-252.5	null
20530.90419	-252.5	null
20537.0056	-252.5	100
20537.0056	-252.5	100
```

https://github.com/projecthorus/sondehub-tracker/pull/360
