### ISSUE TITLE
Multiple Zoom Levels per single mouse wheel click

### ISSUE THREAD

**Issue by swilson317** [projecthorus/sondehub-tracker#273]
A pet peeve of mine is that when I use a mouse wheel to zoom in/out (as you would do for scrolling, not clicking it as a button), each detent of a wheel turn zooms in three times vs. just one. Each mouse wheel click turn, IMHO, should be equal to one level change...just like when clicking the +/- icons to zoom in/out.

**Comment by darksidelemm** [comment]
I am not certain this is actually a tracker issue? 
On my laptop trackpad i can zoom in using scrolling in one level steps just fine.

**Comment by darksidelemm** [comment]
I can also confirm on my Windows PC (Windows 10) + Chrome, one scroll wheel click zooms one level.

**Comment by swilson317** [comment]
Thanks! I will check whether it is a configuration setting. It's a fairly new Logitech Ergonomic mouse. Sorry for the noise.
