### ISSUE TITLE
Predictions outside of schedule list

### ISSUE THREAD

**Issue by Torrehoradada** [projecthorus/sondehub-tracker#274]
During the last days I get often weired prediction data: Sometimes I get predictions for the past, which is not too problematic.
But I get also results which do not reflect the scheduled starts for the starting point in question:
Sometimes there are schedules missing, sometimes there are predictions outside of start schedules.
See the appended HC where are predictions #1,# 2,# 3 for the weekday of sunday, (Dec. 18) at which there is no start schedule on the list, as there are only services from Monday to Friday.

![Bildschirmfoto vom 2022-12-17 00-33-43](https://user-images.githubusercontent.com/35318102/208209919-9ce2e604-6ec9-46bf-bcb4-f0a1a0981e04.png)

**Comment by TheSkorm** [comment]
We've done a bunch of work on how predictions are generated since this issue was created - can you confirm its still an issue?

**Comment by Torrehoradada** [comment]
Hello again,
As far as I can see, this error has been fixed.
