### ISSUE TITLE
distance error

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#275]
hello, I just saw that SondeHub indicated an error on the distance of the probe of about +10km, I checked my GPS point and the one indicated on SondeHub which is identical, but when I click on a probe, the distance is 10km higher than the real distance or by decoding with TTGOs, I took the GPS point of the probe and checked on google maps and I find 10km less than SondeHub indicates to me, thank you

![Capture](https://user-images.githubusercontent.com/87615097/209416604-edfabae7-a1b8-461a-84e5-cc9039e046f9.PNG)

**Comment by darksidelemm** [comment]
This might be because the distance indicated on sondehub is the 'straight
line' distance (which includes the height of the balloon), which will be
longer than the distance over ground.

**Comment by 14ri004** [comment]
Hello mark, I'm thinking about it but 10 km makes a lot of difference, at the same time on RDZsonde and MysondyGo I have 10km less than on SondeHub, I'm going to double check today with two other friends to see if it comes from home (possible), I'll let you know what happens next, thank you and have a good end of the year

**Comment by darksidelemm** [comment]
After looking at the code, I can confirm that the range used is the 'direct' range to the transmitter, wherever it may be in altitude, not the 'distance-over-ground'. 
This is intended, as otherwise if you have a sonde almost above you, the range would be near 0, which is nonsensical.

**Comment by 14ri004** [comment]
indeed mark, after verification the probe was at 32000 m altitude, which could explain the difference in distance, thank you for your answer, and happy new year.
