### ISSUE TITLE
Balloon colors

### ISSUE THREAD

**Issue by coudersport** [projecthorus/sondehub-tracker#276]
Any chance the color yellow could be changed to something darker.  Very hard to see on map

**Comment by 14ri004** [comment]
Same problem, not easy to see on phone in sunlight

**Comment by darksidelemm** [comment]
Doing some tweaking of the yellow colour on testing.v2.sondehub.org 

I've darkened the yellow colour slightly, and also increased the opacity of the prediction traces a little bit.

**Comment by 14ri004** [comment]
hello Mark, no worries on my PC at home, but on my phone and in the car, the yellow color remains very difficult to see on the map with the sun, (blue, green, red) are perfect in mobile.

**Comment by darksidelemm** [comment]
So the current colours in the rotation are:
["red", "blue", "green", "yellow", "purple", "orange", "cyan"];

Are purple, orange and cyan ok? I'm thinking maybe we'll just drop yellow from the rotation.

**Comment by 14ri004** [comment]
actually, giving up yellow would be a good idea, for purple, orange, and cyan colors it's OK, thank you

**Comment by darksidelemm** [comment]
Yellow has been removed from the balloon colour lineup.
