### ISSUE TITLE
Help please... location!?!?

### ISSUE THREAD

**Issue by Pronto2018** [projecthorus/sondehub-tracker#280]
I´m enjoying your apreciated website / app "Sondehub" very much! Just
> a small problem: if I start the website with my windows 10 pc or with
> the playstore app, I´m asked for permission to set my location, I
> allow and averything works well.
>
> If I´m using my android tablet and the app, I´m not asked for give
> permission to use my location; same happens, when I use the website
> with a smart tv; the pop up box with asking to allow / give my
> location, does not appear an so my own location is nut registered?!?!?
>
> What can I do to use your amazing app / website with tablet and smart
> tv browser, included the own location set up???
>
>
> Cheers
>
> Norbert

**Comment by darksidelemm** [comment]
You're going to have to figure out how to enable location services on whatever platform you are accessing SondeHub is on, we can't help with this.

Just remember that location services just puts the 'blue person' on the map, it doesn't do much else.
