### ISSUE TITLE
Retrieve telemetry data

### ISSUE THREAD

**Issue by picupicu** [projecthorus/sondehub-tracker#281]
Hi, is there a way to be able to recover the data related to a Vaisala radiosonde in addition to the "Telemetry Graph" section on the SondeHub Tracker? Is there a download section? An xml file?

**Comment by darksidelemm** [comment]
Yes, there are a few ways to access historical data, though it's all in a JSON format.

The pysondehub library will grab data from our S3 archive: https://github.com/projecthorus/pysondehub/#downloading-archived-radiosonde-telemetry-data

You can also just query our API, e.g.: 
wget https://api.v2.sondehub.org/sonde/U2750302
