### ISSUE TITLE
Small altitude plot issues

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#282]
The small altitude plots in the payload list clearly have some kind of time scale issue, when comparing the data loaded via the API, and the new data coming in via websockets.

<img width="257" alt="Screen Shot 2023-04-10 at 09 12 09" src="https://user-images.githubusercontent.com/1040275/230801948-8ebea674-7ee5-424b-96bf-7f53a0417617.png">

**Comment by darksidelemm** [comment]
It looks like the draw function ( https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L2215 ) doesn't take into account the time values, i think it just assumes the same time step between points, which isn't going to be the case any more, as the data returned by the API on page-load will be decimated.

**Comment by darksidelemm** [comment]
Fix for this is in testing.v2.sondehub.org

**Comment by TheSkorm** [comment]
I believe this is resolved now.
