### ISSUE TITLE
Query S3 as well as ES when in single-sonde mode.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#283]
A query for a sonde that may have been observed some time in the past, but has also been observed relatively recently (within a week or so), can result in only the most recent data.

Suggest also querying S3 for old data when a single-sonde filter is used.

**Comment by 73-de-LZ** [comment]
Not in the right place to comment, but I want to say Thanks for the new version: Tracker Revision: 638c218
Now reports are shown in details, stay long enough and the trajectory is ploted veeeeery well till the smallest detail. Really fine improvement, thank you for all!
