### ISSUE TITLE
problem with the landing point of a probe

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#284]
Hello, when I click on the laying point of a probe, I have coordinates displayed, but impossible to open Google Map to have the route to this position, if I copy the link there is the word (geo) just before the coordinates, which blocks Google Map ---> geo:44.08047,2.38362
and in mobile it is not practical, thank you

![COORDONNEES1](https://user-images.githubusercontent.com/87615097/236175812-2ce64e40-bf67-4e6b-b55f-68636f6a7290.PNG)

![COORDONNEES](https://user-images.githubusercontent.com/87615097/236175833-15c28d71-8894-4527-a19a-a78fcf48e314.PNG)

**Comment by darksidelemm** [comment]
This is meant to be a Geo URI: https://en.wikipedia.org/wiki/Geo_URI_scheme

If you have some other alternative way to handle geographic coordinate links that is compatible across browsers, id be interested to know what it is. Just removing the 'geo:' on the front is unlikely to improve anything.

**Comment by darksidelemm** [comment]
Yeah OK, I can see that these kind of links are handled differently elsewhere on the tracker.

I'll see if i can normalise how they work.

**Comment by darksidelemm** [comment]
Try using https://testing.v2.sondehub.org/ and see if links work on there.

**Comment by 14ri004** [comment]
it works perfectly on my phone, I have the google maps map which opens with the pose point, but on my PC nothing is displayed, may be a problem on my side, I will check, thank you

![1](https://user-images.githubusercontent.com/87615097/236316609-0fb350f3-d58f-45d8-9217-ef06e395e0b7.PNG)

![2](https://user-images.githubusercontent.com/87615097/236316627-70006cef-19e8-464c-ad33-8b12adc91ad4.PNG)

**Comment by 14ri004** [comment]
problem solved, it works now, thanks

**Comment by darksidelemm** [comment]
This change has now been applied to tracker.sondehub.org and amateur.sondehub.org
