### ISSUE TITLE
information lag

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#285]
Hello, on my Samsung S21 I just saw this little anomaly, on the probeHub page the elevation and distance information is out of frame, this does not work on all probes

![Screenshot_20230522_100549_Firefox](https://github.com/projecthorus/sondehub-tracker/assets/87615097/eeaaa172-66c3-44c0-b523-b4c8c1f9369b)

![Screenshot_20230522_100603_Firefox](https://github.com/projecthorus/sondehub-tracker/assets/87615097/33729ee1-8613-4012-a8a2-62987d977638)

**Comment by darksidelemm** [comment]
I don't have an easy fix for this. Is this the stock browser? Does it work in Chrome on Android?

I'm wondering perhaps if your browsers zoom is set somehow, making the text bigger. It certainly looks bigger than on my phone.

**Comment by 14ri004** [comment]
hello mark, it does that on some probes, it's not very serious, it depends on the number of characters that exceeds the width of this small window, it's just for your information, if it does on others nobody, thank you.
