### ISSUE TITLE
Request bursttimer for Meteomodem M20

### ISSUE THREAD

**Issue by lelun** [projecthorus/sondehub-tracker#291]
Hi the meteomodem has a batterylife that lasts for about 4 hours 4.30 if its warm. can sondehub add a burst timer or switch off timer to them thats for about 4hours after sonde is first detected? this would be a nice feature to know if the sonde is close to running out of battery.

otherwise love the site and the updates makes it a joy to use. 
Mvh lelun

**Comment by darksidelemm** [comment]
Sorry, this is not something we can do easily. The information we display must be from the radiosonde telemetry itself, not something generated like that...
