### ISSUE TITLE
If the users location is known - default map location to there rather than UK

### ISSUE THREAD

**Issue by xssfox** [projecthorus/sondehub-tracker#292]

**Comment by scottjpalmer** [comment]
Thanks. I should've suggested it sooner.

Love your work team, keep it up!

**Comment by scottjpalmer** [comment]
Hi

Can I give this a nudge please?

Thanks

**Comment by darksidelemm** [comment]
This is actually a bit difficult, as many browsers wont give geolocation information until the user interacts with the page first, so we don't always get location on page load...

**Comment by scottjpalmer** [comment]
Ahh, understood. Great to see it being discussed on Discord, thanks. Accurate location isn't what I'm after, just to have it open vaguely in current region rather than on the other side of the world would be great. Cheers.

**Comment by argilo** [comment]
The site now remembers the last map location & zoom level (#343), which solves the problem of the map always starting with the UK. It's still necessary to click on the coordinates in the upper left corner to scroll to your current location.

**Comment by scottjpalmer** [comment]
Thanks! Works well.

**Comment by TheSkorm** [comment]
https://github.com/projecthorus/sondehub-tracker/pull/372
