### ISSUE TITLE
photo of the barcode in Report Recovery

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#299]
Hello, is it possible to add a function in probehub, during recovery to be able to add a photo of the barcode of the probe in Report Recovery, this in order to avoid fakes, thank you

**Comment by darksidelemm** [comment]
This is not something we want to deal with, sorry. We do not have the time to deal with verification, handling of images, etc...  

You can always report a recovery a second time if you actually find the sonde - the latest information is what is shown on the tracker.

I'm surprised this is really such a big issue where you are? We don't seem to have these kinds of issues over here in Australia!

**Comment by 14ri004** [comment]
this is absolutely not THAT BIG a problem, neither here nor elsewhere, but a simple question of whether it was possible OR NOT to add a photo, to the recovery of a probe, A SIMPLE QUESTION, that's all ...

**Comment by darksidelemm** [comment]
In which case the answer is a simple no. This is not something we wish to implement.

**Comment by 14ri004** [comment]
Thank you for that answer
