### ISSUE TITLE
hPa pressure Sondehub

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#303]
hello, when the hPa pressure reaches 0 (zero) the result goes to 4095 hPa, often when the probe exceeds its theoretical height of 35000m, until the moment it bursts, the pressure returns to normal up to sea level .

![Capture](https://github.com/projecthorus/sondehub-tracker/assets/87615097/4b373657-8d21-46eb-bdf9-3d9ba79d99bd)

**Comment by darksidelemm** [comment]
Not much we can do about this - this value is what the sonde is reporting! 
The grafana plots show that this is most likely the pressure sensor on the sonde reporting incorrectly at very low pressures.
https://grafana.v2.sondehub.org/d/bbaa7894-e5f4-4c0d-be96-897b4ffde43b/radiosonde-telemetry-dashboard?var-Serial=210-2-01994&from=1698491785000&to=1698501116000&orgId=1 

I've seen this from quite a few different MEMS pressure sensor types, which is what the M20 is using.

**Comment by darksidelemm** [comment]
Going to close this one, as there isn't much we can do about this.
