### ISSUE TITLE
Burst point

### ISSUE THREAD

**Issue by Mauri740** [projecthorus/sondehub-tracker#307]
Is it possible to improve the design of the balloon burst point? The current one is unclear. Thank you

**Comment by darksidelemm** [comment]
By this do you mean how it's not that visible? Maybe we could add a darker
shadow effect so it has more contrast...

**Comment by Mauri740** [comment]
a darker effect would be great. Thank you

**Comment by 14ri004** [comment]
hello, still very little visible the bursting point, we must think of people with vision difficulties, thank you

**Comment by darksidelemm** [comment]
I haven't had time to work on this yes, sorry. 
The burst icon is here: https://github.com/projecthorus/sondehub-tracker/blob/master/img/markers/balloon-pop.png
If you can figure out a way to make it a bit more opaque, or with some kind of shadow, I'd be happy to test it.

**Comment by Mauri740** [comment]
could it be something like this?
<img width="20" alt="NEW balloon-pop" src="https://github.com/projecthorus/sondehub-tracker/assets/139569966/8f539def-f0aa-4fcb-b08d-a1e2a8bd8e80">

**Comment by 14ri004** [comment]
mauri740's version is more visible, that would be perfect

**Comment by darksidelemm** [comment]
This doesn't look like a transparent PNG to me? It *must* have transparency enabled.

**Comment by darksidelemm** [comment]
A quick bit of color-to-alpha in Krita, and things are looking better:

Old Icon:
<img width="405" alt="Screen Shot 2024-01-09 at 07 53 25" src="https://github.com/projecthorus/sondehub-tracker/assets/1040275/d250a3df-9dff-4d94-b7b5-da997625d253">

New Icon:
<img width="246" alt="Screen Shot 2024-01-09 at 07 59 49" src="https://github.com/projecthorus/sondehub-tracker/assets/1040275/ef5dffc6-7765-438d-a7e4-b619582db481">

**Comment by darksidelemm** [comment]
This is now live on https://testing.v2.sondehub.org/ (noting that your browser cache might hold the old marker).

Let me know what you think.

**Comment by Mauri740** [comment]
It's perfect, excellent visibility. Thank you

**Comment by darksidelemm** [comment]
This has been rolled out to sondehub.org and amateur.sondehub.org
