### ISSUE TITLE
Meisei iMS-100 no longer being displayed

### ISSUE THREAD

**Issue by Choong-9M2CEI-9V1CV** [projecthorus/sondehub-tracker#308]
Since morning of 1st January 2024. SondeHub can no longer display the Meisei iMS-100 radiosondes launched by Singapore. However, the same sondes can be displayed on radiosondy.info without issues. 

The followings are the affected sondes so far: 

3rd Jan (Wen), PM session: 2107544 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS202898)
3rd Jan (Wen), AM session: 2107548 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS20289C)
2nd Jan (Tue), PM session: 2107549 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS20289D)
2nd Jan (Tue), AM session: 2107542 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS202896)
1st Jan (Mon), PM session: 2107550 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS20289E)
1st Jan (Mon), AM session: 2107538 (https://radiosondy.info/sonde_archive.php?sondenumber=IMS202892)

**Comment by darksidelemm** [comment]
OK, I'm not seeing any data from these radiosondes in the sondehub database at all.
Have you been seeing any errors when telemetry is being uploaded?
Could you upload a log file for one of these sondes so we can see if there is something weird about the data?

**Comment by darksidelemm** [comment]
Also, if you can't easily access your auto_rx 'system' log (where any errors will be showing up), enable your system log by setting this entry to true: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L453
This will then produce log files ending in _system.log in your log directory.
Uploading one of these will hopefully help shed some light on the situation.

**Comment by Choong-9M2CEI-9V1CV** [comment]
Here is the log for sonde ID 2107538 from Mr Zaki 9M2ZAK's receiving station: 
https://drive.google.com/file/d/1toDsG4m34aFXx6mhVGtelA7n1_mKThGT/view?usp=sharing

**Comment by darksidelemm** [comment]
Nothing seems particularly amiss there. Do you have a system log you can send me please?

**Comment by darksidelemm** [comment]
Actually, I see that the file ends exactly at 23:59:59Z! Suggesting that no data after that was successfully logged (to the log file, at least).

Hopefully your system log shows some errors that will explain whats going on.

**Comment by Choong-9M2CEI-9V1CV** [comment]
I tried with one of the iMS-100 radiosondes (ID: 2102837) I recovered on 20th June 2023. Here is the system log: 
https://drive.google.com/file/d/1tyclyFcfIrrA2RA_rgF_tqA5Ll0zVE6K/view?usp=sharing

**Comment by darksidelemm** [comment]
This error could have easily been because the sonde you were testing with did not have GPS lock.

What I need from you to help debug this issue is:
- Confirmation that when **receiving a Meisei sonde in the air**, you are still seeing the sonde in the auto_rx web interface, and that it is being uploaded to APRS (radiosondy)
- Your system log from a time when a Meisei sonde **is in the air** and being received.

I also ideally need a recording of a Meisei sonde in the air. You can setup auto_rx to save IQ data during a radiosonde reception by setting the save_decode_iq setting to True ( https://github.com/projecthorus/radiosonde_auto_rx/blob/master/auto_rx/station.cfg.example#L508 ). Note that this will produce some very large file in your log directory. The recordings will start with decode_IQ
I need one of these recordings from when there is a sonde in the air to be able to properly test any fixes to the current issue.

**Comment by rs1729** [comment]
Perhaps the problem is the new year 2024
https://github.com/rs1729/RS/blob/a287b3f2ac9b91b7d382ab6a0933f69eebea8c0a/demod/mod/meisei100mod.c#L1131
Would not surprise me. Back then I identified only one digit for the year, the oldest samples I had were from 2013/2014.
Would be great, if someone had raw data or recordings from 2024.

**Comment by Choong-9M2CEI-9V1CV** [comment]
While waiting for Meteorological Service Singapore (MSS) to release another balloon in the evening, we were experimenting with the radiosonde on-hand. 

I made two changes in the **auto_rx.py**: 
https://drive.google.com/file/d/1u7WqKpJcn70sUPtyd8zc-MzIP5wGLjeJ/view?usp=sharing

Now I can clearly see that the payload timestamp is exactly 10 years behind the system timestamp (aka the correct timestamp): 
https://drive.google.com/file/d/1uE_aFIbEtPnmtkYEOORatu_IjPRaM1tc/view?usp=sharing

I couldn't get my auto-rx to save the audio in wave format, even though I have enabled both **save_detection_audio** and **save_decode_audio**. I only managed to see the saved file in raw format: 
https://drive.google.com/file/d/1uEfQkm6bUuT8QbaL5bOhKCb5rbP-xLBa/view?usp=sharing

And here is the recorded IQ data (after enabling **save_decode_iq**): 
https://drive.google.com/file/d/1uFsqmrRj90jdaXpLxeKtNcXJ2za50FqW/view?usp=sharing

My friends suggested me to record the baseband with a Windows machine running SDR#. So here's the recorded wave files, in 16-bit PCM IQ format (in the order of ascending file size): 
https://drive.google.com/file/d/1uPIy-Bo-npCK-tvVe1HK3ugaHNnP0PSj/view?usp=sharing
https://drive.google.com/file/d/1uQfoAKe2so-vTg-ukLzxjNZeB6wFMkhU/view?usp=sharing
https://drive.google.com/file/d/1uOkyjIPJITZ6Rl66GCnhcc1S0yzEG5Hn/view?usp=sharing

Be reminded that all the files above are based on the radiosonde on-hand, ID 2102837.

**Comment by Choong-9M2CEI-9V1CV** [comment]
I made a mistake while recording the baseband on SDR#: The freq was off. 
So, please retune to 401.9MHz when replaying the files. Sorry for the inconvenience caused.

**Comment by darksidelemm** [comment]
OK, so the year issue will be one of the main ones blocking data from being processed in Sondehub.

However, it should also result in all packets being dropped immediately by auto_rx, so I'm somewhat confused that anything is getting into radiosondy.info - unless someone figured out the year issue and has set their sonde_time_threshold to something extremely large.

**Comment by rs1729** [comment]
Updated meisei100mod.c
https://github.com/rs1729/RS/blob/test/demod/mod/meisei100mod.c
for testing.
Default decade is now 2020..2029. This corresponds to ref_yr=2024.
For older recordings one can set the (reference) year "`--year <yr>`" such that the last digit `d` of the year in the raw data belongs to a year in `yr-4 .. yr-4+9`.

**Comment by Choong-9M2CEI-9V1CV** [comment]
Here is the recorded IQ data from the iMS-100 launched this evening (thanks to Mr Zaki 9M2ZAK): 
https://drive.google.com/file/d/1uTwQB0MuxPS2o8Z2ZLXE96HYZnNHsX27/view?usp=sharing

**Comment by darksidelemm** [comment]
OK, I've pushed out the changes from @rs1729 to both the Master and Testing branch, and done a 'bugfix' release: https://github.com/projecthorus/radiosonde_auto_rx/releases/tag/v1.7.1.1

If you're using docker, the images will still be building for a while (check here for progress: https://github.com/projecthorus/radiosonde_auto_rx/actions ) but if not, you should be able to update now.

**Comment by darksidelemm** [comment]
OK, another version bump because the 1.7.1.1 version broke the version checks. Now at 1.7.2 in Master, and 1.7.3-beta4 in testing. Builds are in progress.

**Comment by darksidelemm** [comment]
I saw a few stations uploading using the testing branch before the morning sonde landed - so it looks like it's working!

https://tracker.sondehub.org/#!mt=Mapnik&mz=10&qm=3h&mc=1.35257,103.15681&f=2107543&q=2107543

**Comment by Choong-9M2CEI-9V1CV** [comment]
Thank you all for helping us out with this issue. 73, de Choong 9M2CEI/9V1CV.
