### ISSUE TITLE
Manual entry of burst altitude in predictions.

### ISSUE THREAD

**Issue by 73-de-LZ** [projecthorus/sondehub-tracker#309]
If I remember well, there was an option to manually enter the burst altitude used by prediction for a given site.  I miss that option very much, as now model got the burst altitude probably based on average for longer period and this lead to some great inaccuracies. We never know when exactly the baloon will burst,  but if the prediction get average from smaller period, let say 3 days, I suppose it will be more adequate. Or better to have a field to enter manually a different than suggested value of burst altitude.
73!

**Comment by darksidelemm** [comment]
The predictions are run in the sondehub backend, based on our launch site database, so adjusting these values 'on the fly' is not really practical.  The averaging is also done as a 'batch' job, not automatically, so running that over the last few days of data is also not easy to do - we would prefer that there is some human input into the chosen values too, to ensure they don't end up with some weird values.

There was never an option for manually entering in the prediction data - maybe you are thinking of the SondeHub Launch Site Modification Suggestion Form (which is accessed from each of the launch site popups), or perhaps the [per-payload prediction settings](https://github.com/projecthorus/sondehub-amateur-tracker/wiki/Getting-your-Flight-on-the-Sondehub-Amateur-Tracker#flight-predictions) on amateur.sondehub.org.

If you want to be able to customise the predictions on a per-flight basis, then I'd suggest running something like [ChaseMapper](https://github.com/projecthorus/chasemapper) at your station, where you can adjust the prediction parameters however you like. I believe the rdz_ttgo_sonde livemap also has custom prediction settings.

**Comment by 73-de-LZ** [comment]
Thank you, you are 100% correct on everything. And yes, I mixed up with amateur.sondehub.org, but will take a look at the ChaseMapper. RDZ livemap have also that settings, but for the current fly, no prediction for the next few days. I have observed that under some conditions:
even sondes that usually goes higher to 35km, as Vienna for example, sometimes they burst earlier at lower altitude and when this happens usually happens also to the nearest sites, maybe it could be something related to the pressure at higher altitudes, never researching deeply the reason, but my observations is confirmed few times and I don't think it is just a coincidence, but not 100% sure. 
73!

**Comment by 73-de-LZ** [comment]
Just to be sure that I am explained well what I mean:
If it is possible the "Average burst altitude" to be in a editable field, so when we press generate predictions they to be generated with burst altitude from that field.
Not important, but could be useful for better short-term prediction for the next few days.
![Screenshot_20240112_200656_Chrome](https://github.com/projecthorus/sondehub-tracker/assets/16052106/7f14ca95-25d9-4f22-843a-3f8358fce661)

**Comment by darksidelemm** [comment]
I would prefer to not add custom fields to that popup box.

If you want to do forward-looking predictions for a launch site using custom burst altitude (and I guess descent rate) parameters, then the appropriate tool is https://predict.sondehub.org

For live predictions, then Chasemapper is the appropriate tool.

**Comment by 73-de-LZ** [comment]
Yeeees, that was the tool I searching for and somehow miss it.
Thaaaaank you, great!
