### ISSUE TITLE
ChaseMapper 

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#310]
hello, quick question, is there a possibility to make ChaseMapper work under Windows or not???, thank you

**Comment by darksidelemm** [comment]
This is not the right place to be asking questions about chasemapper - the chasemapper repository is the appropriate place: https://github.com/projecthorus/chasemapper/issues

Anyway, as chasemapper is written in Python, it will probably run under Windows, but it's not something I can provide any support on. I generally expected chasemapper to be run on something like a Raspberry Pi, alongside a radiosonde_auto_rx installation.
