### ISSUE TITLE
probe history

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#312]
hello, would it be possible to have in the search history, the possibility of having on the map only the probes recovered???, thank you.

**Comment by darksidelemm** [comment]
Not sure what you are asking here.
Right now you can search for historical launches for each launch site, and the icon indicates if the sonde was recovered or not. That's about the extent of what we can easily do.

**Comment by 14ri004** [comment]
hello, what I am asking and if it was possible to have a function in the history, to only see the recovered probes displayed on the map, instead of having the 700 probes from the center over 1 year .

**Comment by darksidelemm** [comment]
At this point, this is not possible on the tracker. It could be added, but we're running out of space on the launch site popup dialog. 
This sounds like something that would be better on a separate website. The recovered sondes API supports requesting recoveries around a user-defined lat/lon.

**Comment by 14ri004** [comment]
hello, there are a lot of probes lost at 20000 or 30000m this slows down the display with more than 700 probes per year, many of which fall either at sea or break down, it's a shame, thank you all the same for your work.
