### ISSUE TITLE
Archived data from an ozone sensor survey

### ISSUE THREAD

**Issue by robertimgw** [projecthorus/sondehub-tracker#316]
Hey

Is it possible to recover complete data from ECC ozone sensors from several weeks or several months ago?
Is this data archived on the receiving station terminals or on the anyside?

**Comment by LukePrior** [comment]
Should be available in S3

**Comment by LukePrior** [comment]
http://sondehub-history.s3-website-us-east-1.amazonaws.com/#date/

**Comment by darksidelemm** [comment]
If you know the serial number of the radiosonde associated with the launch, then the easiest way to dump the data is using pysondehub: https://github.com/projecthorus/pysondehub?tab=readme-ov-file#downloading-archived-radiosonde-telemetry-data

Note that we only decode the XDATA on the tracker website frontend, so it'll just appear in the telemetry as a hex string.
