### ISSUE TITLE
Tooltips for blue/green rings

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#319]
We've had some questions as to what these rings represent, so perhaps we should have a hover-over tooltip.

Blue ring: Line-of-right (radio) horizon of the payload.
Green ring: Payload is greater than 5 degrees above the horizon within this circle, which indicates it should be fairly easily receivable.

**Comment by smwnwrght** [comment]
I hadn't realised that! It may be easier to just add this info to the user guide.

**Comment by TheSkorm** [comment]
Putting it on the edge of the circle is a little annoying. For now I've placed it on the "title" (where the km is listed) which is probably good enough?
<img width="599" alt="image" src="https://github.com/user-attachments/assets/0617ab12-ddea-4d43-bb35-09d882f8db28">
<img width="567" alt="image" src="https://github.com/user-attachments/assets/e82941e2-d62f-4bb6-af0c-64edc9c4791f">

**Comment by TheSkorm** [comment]
In https://testing.v2.sondehub.org
