### ISSUE TITLE
apple-touch-icon.png needs updating from HabHub to SondeHub branding, larger size

### ISSUE THREAD

**Issue by drive-c** [projecthorus/sondehub-tracker#321]
### Issue
[img/apple-touch-icon.png](https://github.com/projecthorus/sondehub-tracker/blob/master/img/apple-touch-icon.png) reflects the old HabHub logo and branding and not the SondeHub branding. Additionally, this icon is 144x144 instead of the more recent recommended touch icon size of 180x180.

![iOS home screen and Safari bookmark icon](https://github.com/projecthorus/sondehub-tracker/assets/15067932/19213a65-7094-4641-a51f-8346f0ebc283)

### Recommended change
Use the wordless icon at [img/icons/maskable_icon_x192.png](https://github.com/projecthorus/sondehub-tracker/blob/master/img/icons/maskable_icon_x192.png) scaled at 100% in a 180x180 frame, like the version uploaded here.

![Example new Apple touch icon](https://github.com/projecthorus/sondehub-tracker/assets/15067932/c4d515a2-d532-45db-b0a4-fff449a3f087)

**Comment by TheSkorm** [comment]
Deployed to testing.v2.sondehub.org (https://github.com/projecthorus/sondehub-tracker/pull/365)
