### ISSUE TITLE
GPS position on Sondehub

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#322]
hello, I have a little problem with the GPS position on Sondehub, when I am at home on the box, the position is good, but when I use my laptop in the car with the 4G LTE network, my GPS position from Sondehub and completely shift by 700/800 Km, I searched and I couldn't find it, an

<img width="510" alt="gps" src="https://github.com/projecthorus/sondehub-tracker/assets/87615097/58e1b054-3165-4f37-935c-982f54d0f597">
d neither solved this problem, if anyone has a solution, thank you in advance.

**Comment by darksidelemm** [comment]
Closing as this is a duplicate issue of #323
