### ISSUE TITLE
GPS position on Sondehub

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#323]
hello, I have a little problem with the GPS position on Sondehub, when I am at home on the box, the position is good, but when I use my laptop in the car with the 4G LTE network, my GPS position from Sondehub and completely shift by 700/800 Km, I searched and I couldn't find it, and neither solved this problem, if anyone has a solution, thank you in advance.

<img width="510" alt="gps" src="https://github.com/projecthorus/sondehub-tracker/assets/87615097/58e1b054-3165-4f37-935c-982f54d0f597">

**Comment by darksidelemm** [comment]
This is not an issue that we can easily solve on SondeHub. We rely on browser location services for your device location, and if your browser can't figure out where you are, then neither can we.

While mobile devices like a mobile phone might have access to cell tower information or an internal GPS to figure out where you are and provide this to the browser, a laptop computer won't generally be able to do this. If you are trying to use the sondehub tracker for chasing sondes in this way with a laptop, then this is unlikely to work.

I would recommend using a dedicated balloon chasing application like ChaseMapper, with a USB GPS receiver so it knows your location accurately: https://github.com/projecthorus/chasemapper

**Comment by 14ri004** [comment]
hello and thank you for your answer, I use a T-BEAM in the car, what is strange is when I am in my yard connecting to 4G the position is good, I move 500m, probehub positions me at 500km, I move 20km and Sondehub positions me at 1000km, I come back home Sondehub positions me exactly above my house, I don't understand the huge shift in GPS position via 4G, it's not very serious, but annoying, and if I use windows or linux the position is not the same, I will deal with it and that does not prevent me from recovering RS, but it was just to know if there was a possible solution, thanks

**Comment by darksidelemm** [comment]
Unfortunately we have no real control over that browser location services presents to us... This is up to the browser and the OS.
