### ISSUE TITLE
Discussion - generate balloon/car icons with a script

### ISSUE THREAD

**Issue by bismurphy** [projecthorus/sondehub-tracker#326]
Currently, in `img/markers`, there are a large number of files which match the pattern of `balloon-{COLOR}.png`, `car-{COLOR}.png`, `parachute-{COLOR}.png`, etc. These appear to have been committed over 11 years ago.

It is not clear where these images come from. Many of them were committed by @rossengeorgiev 10+ years ago. I imagine there is an SVG that these were generated from.

It would be nice if we could have a process to generate these images, ideally a Python script that takes a basic image (something like `car_base.png`, `balloon_base.png`, etc (or, again, SVG files), and can automatically generate whatever colors we want. For example, there is currently a Green color for cars, balloons, and parachutes, but it would be nice if we could try having a Light Green and Dark Green. The more colors we have, the lower the changes for two nearby objects to share a color, which means better ability to tell objects apart. Of course it is possible to use an image editor of choice to modify an existing image to be a different color, but I think it would be an improvement if the sources for the images were present in the repository and available for anyone to adjust the set of colors moving forward. It would even be possible to have the image generation exist as a step in the build process for the repository, though that is not strictly necessary.

I would be happy to work on writing a script to do the color generation, but I first wanted to start a discussion to see anyone else's thoughts, or if there are any known SVG files (or other files) out there that I'm missing.

**Comment by TheSkorm** [comment]
I think this is done now?
