### ISSUE TITLE
HTTP Query with Location, Map Type&Zoom, and Time Limit Data?

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-tracker#33]
Hi,

Up until recently, I've been using a URL shortcut that would take me to the SondeHub tracker website, but would also set the desired location, map type and zoom, as well as the time limit for sonde filtering.
I think that the recent changes might have rendered that link almost useless.

Is there still a way to achieve what I'm after?

@darksidelemm, @TheSkorm @LukePrior: As always - thanks for all the hard work! This is all very much appreciated.

**Comment by LukePrior** [comment]
Can you provide some more information on the URL you are using most of the url options should be the same except for maps.

**Comment by ZigiWalter** [comment]
Wow, that was fast :-)

https://tracker.sondehub.org/?sondehub=1#!mt=osm&mz=7&qm=6_hours&mc=12.3456,12.3456

**Comment by TheSkorm** [comment]
I think this does the same thing? https://tracker.sondehub.org/#!mt=Mapnik&mz=5&qm=6_hours&mc=12.3456,12.3456

**Comment by ZigiWalter** [comment]
Thanks - it's better, but isn't the duration value still ignored?

**Comment by ZigiWalter** [comment]
Also - I get it that the values need to be crafted "manually", as adjusting the display no longer updates the URL query, correct? (maybe an "export button" would do that?)

**Comment by LukePrior** [comment]
> Thanks - it's better, but isn't the duration value still ignored?

It does actually search for 6 hours but the dropdown doesn't update on ititial load

**Comment by LukePrior** [comment]
> Also - I get it that the values need to be crafted "manually", as adjusting the display no longer updates the URL query, correct? (maybe an "export button" would do that?)

I'm going to look into adding that functionality back

**Comment by LukePrior** [comment]
I would also switch to https://sondehub.org/#!mt=Mapnik&mz=5&qm=6_hours&mc=12.3456,12.3456 if you want to take advantage of PWA

**Comment by ZigiWalter** [comment]
What is "PWA"...?

**Comment by LukePrior** [comment]
> What is "PWA"...?
> Do you refer to this?
> https://en.wikipedia.org/wiki/Progressive_web_application

Yep if you are on a modern browser you should see the option to install the webpage.

**Comment by LukePrior** [comment]
@ZigiWalter the URL should now automatically update and the time box should get the right value.

**Comment by ZigiWalter** [comment]
Thanks! Something is strange though, at least on my end:
If I take a valid link (=one generated by the GUI) and paste it into a new web browser tab, the query gets ignored (it shows the default SondeHub view). Only if Ipaste again in the same tab and hit "enter" it will respect the specific query.
I've tried both Firefox and Chrome.

The query I'm trying:
https://sondehub.org/#!mt=Mapnik&mz=9&qm=6_hours&mc=1.23456,1.23456

Is it only me...?

**Comment by LukePrior** [comment]
> Thanks! Something is strange though, at least on my end:
> If I take a valid link (=one generated by the GUI) and paste it into a new web browser tab, the query gets ignored (it shows the default SondeHub view). Only if Ipaste again in the same tab and hit "enter" it will respect the specific query.
> I've tried both Firefox and Chrome.
> 
> The query I'm trying:
> https://sondehub.org/#!mt=Mapnik&mz=9&qm=6_hours&mc=1.23456,1.23456
> 
> Is it only me...?

Seems to work ok with me maybe try Shift-f5

**Comment by ZigiWalter** [comment]
No go.
So you actually get a map showing only a sea (rather than the default map of Great Britain) when you click the above link? Very strange...
Will wait for someone else to report whether it works or not on his/her end...

Thanks again.

**Comment by LukePrior** [comment]
> No go.
> So you actually get a map showing only a sea (rather than the default map of Great Britain) when you click the above link? Very strange...
> Will wait for someone else to report whether it works or not on his/her end...
> 
> Thanks again.

Hi, I've made some changes could you please try again?

**Comment by ZigiWalter** [comment]
I think it's working fine now, thanks again!
