### ISSUE TITLE
Update popup need additional info.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#334]
I've had a few users reporting some confusion as to why they keep seeing the 'This version of sondehub is out of date' popup. 
The answer is that they probably need to clear our their browser cache, or do a shift-refresh, but the pop just says to refresh. 
It might be good to modify the text to provide more detail on what to do.

**Comment by TheSkorm** [comment]
<img width="682" alt="image" src="https://github.com/user-attachments/assets/6111125c-2dbb-4c5c-af36-679b6a9f6f34">
sondehub index page no longer sets cache-control so hopefully this won't be required.
