### ISSUE TITLE
Can't follow the predicted path using the telemetry chart anymore on firefox

### ISSUE THREAD

**Issue by helioshk** [projecthorus/sondehub-tracker#348]
Hi,

Since the update a few days ago, I can't follow the predicted path anymore using firefox. On chromium it works fine.
The blue marker is stuck at the last known position:
![Untitled](https://github.com/user-attachments/assets/98c8d012-7447-4fac-ace7-30113222f466)

With chromium, the blue marker follows the predicted path.

**Comment by TheSkorm** [comment]
Can you please see if https://testing.v2.sondehub.org has fixed the issue?

https://github.com/projecthorus/sondehub-tracker/pull/349

**Comment by helioshk** [comment]
Yes, that seems to fix the problem. Thanks!

**Comment by helioshk** [comment]
I just noticed a second possible issue:
When zooming in the telemetry graph, the selection is losing the mouse focus, as soon as there is new data loaded. So it might be difficult to select a range if there is new data coming in.

**Comment by TheSkorm** [comment]
I don't think this functionality has changed but I've logged a new issue to cover it : #351

**Comment by helioshk** [comment]
TU 🦊 73
