### ISSUE TITLE
Sondehub is out of date message

### ISSUE THREAD

**Issue by nerdoug** [projecthorus/sondehub-tracker#384]
Sondehub has recently started giving a message in lower left corner of main display stating that "This version of SondeHub is out of date. Click here to reload. Page will reload automatically in  23:46:09

A bit awkward, since message covers the icon to go to the full window map. (workaround is to display telemetry graph temporarily.)

Clicking the embedded link, or killing browser and re-entering sondehub.org doesn't have any effect. Likely something silly that I'm doing. Message snip attached.

Doug Elliott / canoe.eh@gmail.com / (519) 630-8925

<img width="205" alt="image" src="https://github.com/user-attachments/assets/95d80547-556d-48c3-817f-3aa1d4a8ae5a">

Awesome tool for balloon chasers - keep up the great work!

**Comment by darksidelemm** [comment]
Hi Doug,

Just a refresh may not properly clear your cache. You may need to go into your browser history and clear your browser cache for it to download the latest files.

Cheers,
Mark

**Comment by TheSkorm** [comment]
After this version the issue reloads should work correctly
