### ISSUE TITLE
Filter by Distance?

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-tracker#39]
Hi,

First, I would like to write that the recent changes done in sondehub-tracker resulted in a noticeable speed-up when used on a cell phone. Thanks for that!

However, I suspect that during peak hours, the app is still sluggish compared to off-hours. It seems to be related to the processing done on the phone (e.g., updating the display when moving/scrolling), rather than network/server load issues.

 I've noticed that there's an existing API call that filters the sondes by distance (https://github.com/projecthorus/sondehub-infra/wiki/API-(Beta)#sondes). Is it feasible to use it (or something similar) in the web app, to limit the sonde list to a configurable distance from the location of the device...?

Thanks.

**Comment by LukePrior** [comment]
We use the /datanew API for legacy reasons which makes this a bit harder.

**Comment by LukePrior** [comment]
I think we've reached the limits on easily implemented speed improvements but I would recommend disabling horizon circles and title markers in the settings tab if you haven't done so already. I find that with these settings disabled I get respectable performance.

**Comment by ZigiWalter** [comment]
Thanks (I'm already disabling the horizon rings, not just for performance reasons :-) )
I understand this feature is not straight forward - let's close this ticket until something changes.

Thanks again.
