### ISSUE TITLE
my device not shown on sondhub map

### ISSUE THREAD

**Issue by DL1WM** [projecthorus/sondehub-tracker#392]
Hi, I am dl1wm and I am using a RDZSonde device to receive weatherballoons and to send their data into the internet and to Sondehub.org. In the beginning my station was shown on the map under my location togwthwr with infos (Antenna, device). Now this is no longer the case.
On the main page of my RDZSonde screen under Sondehub the following message is diplayed:
State: DNS lookup. Last upload start: -1 s ago
Last reply: DNS lookup failed for api.v2.sondehub.org
Can you help me?
In any case many thanks for the wonderful service to the community!
73 de
Wolfgang, DL1WM

**Comment by darksidelemm** [comment]
Since this is a DNS lookup issue, this is going to be a local network issue rather than an issue with Sondehub...
