### ISSUE TITLE
Suggestions for new features

### ISSUE THREAD

**Issue by krivulak** [projecthorus/sondehub-tracker#395]
Hello, 
being new to this hobby I find Sondehub to be incredibly useful. But there are a couple of issues and features missing for the site to be perfect.

1. Adding a way to record sonde location manually. Ideally by putting a marker into the map and filling the info. 
Big portion of the sondes are landing into areas where there is no network coverage. For putting up the information about the sonde you need to go usually quite far just to get back online and that throws your location off. For example the sonde V5050436 I was searching for today - the landing zone is about 5 kilometers East of last recorded frame (more frames received later by TTGO). I wanted to mark the spot for others for future attempts of recovering but had to walk about a kilometer away to get to signal and in the end the position was marked on the spot of last received frame. Car location was way off too.
2. Search button missing in mobile version of the website. There is no way of searching for sondes older than 12 hours on mobile. Filling the ID to the address link is hit or miss, sometimes it works, sometimes it doesn't open anything. Quite crippling while on foot in field.
3. Missing sonde information in mobile version of the website. You have to open Plots to search for sonde frequency. At least the transmitting frequency value should be visible right when the sonde information is opened.
4. Adding button for mobile version of the website to change to desktop version. It is very painful to use the full desktop version on phones but sometimes you need to access the full version to get the info previously mentioned as you cannot access it on mobile version.
5. Adding button for location refresh. Think of a button like Google Maps have. There should be a similiar one to refresh your position on a map. Sometimes I use the Sondehub in field to locate myself and measure how far I am from the recorded dropzone. Reloading website works in about 40% of cases, other times it either puts me on last location or removes my location alltogether. This also makes troubles with recovery announcing as it can throw you WAY off your real location.

I'm not a programmer so please take these notes as ideas for future development. Thank you

**Comment by darksidelemm** [comment]
A few notes:
- Sonde recovery - we are working towards a separate recovery reporting website, which would have the ability to 'adjust' the last reported position to where you know it actually landed.
- Mobile limited data issues in general - This is very much a tradeoff in screen real estate. I think almost everything you are after is available by just rotating your phone into landscape mode.
- Location Service issues - Enable chase car mode. This enables higher precision and more frequent updates of your position.. and also lets others know that you are out chasing.  

Here's some screenshots from my phone:

Portrait mode:
![unnamed1](https://github.com/user-attachments/assets/f1243e2b-2a5b-414a-a8e0-e3346d0e902a)

Landscape mode (search box, frequency, etc all now visible):

![unname2](https://github.com/user-attachments/assets/2df24ffa-a98c-4145-922b-b26dbb517d22)

Browser settings showing 'Desktop Site' option... though I don't think it's necessary: 
![unname3](https://github.com/user-attachments/assets/2fea1a15-d6e9-4342-9a9a-7eb9f348f510)

**Comment by 14ri004** [comment]
Hello, another solution, use a tablet, mobile or portable it is much better with a 10" screen or more

**Comment by krivulak** [comment]
Hello, 

thanks for suggestions. Yeah, the landscape mode is something I didn't try because I never use landscape mode for anything. That is a good point.
The desktop mode is not working on iPhones, only on Android. I don't use the web on Android because it is kinda poorly optimised. While iPhone is refreshing butter smooth on 60FPS, Android does it in single digits and lags very badly. Both phones are comparable quality and performance-wise. You can compare it yourselves by number of received and processed messages. 
Android:
![Screenshot_20241220-132220528](https://github.com/user-attachments/assets/3989ff7a-0c15-4f09-9903-e30c328ff81e)
And it feels very choppy, it lags a lot and moves poorly

iOS:
![IMG_5596](https://github.com/user-attachments/assets/8c64c98b-b16b-4d65-a562-9c6312a0f8b8)
Smooth like butter

**Comment by xssfox** [comment]
What phone is the android phone? Pixel 8a renders ok for me. There's probably not many more performance improvements we can do as we are somewhat bound by leaflets performance - its just the shear number of elements we  are trying to update on the map becomes a problem.

Not sure why desktop mode wouldn't be working on ios. I think we've removed most of our ios specific code. I don't have an iphone to test with however so will probably need someone else to look into.

You shouldn't need to refresh the page to get updated location if chase is enabled - however your browser might not be sending us the latest position for some reason

**Comment by xssfox** [comment]
Separated out the issues we can work on into seperate issues so we can track them individually
