### ISSUE TITLE
Add filter by Radiosonde Type

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#5]
Add a dropdown box on the top bar, next to the search box (or perhaps we can make use of the filter box somehow?) to allow filtering by radiosonde type.

Support for this kind of filtering also needs to be added to the Sondehub API. Since the radiosonde 'subtype' (e.g. RS41-SGP) data is not always available, we will have to filter by the 'top level' type (e.g. RS41, DFM, M10...).

**Comment by LukePrior** [comment]
This is now in the latest testing branch with the following supported options:

`["RS92", "RS92-SGP", "RS92-NGP", "RS41", "RS41-SG", "RS41-SGP", "RS41-SGM", "DFM", "DFM06", "DFM09", "DFM17", "M10", "M20", "iMet-4", "iMet-54", "LMS6", "LMS6-400", "LMS6-1680", "iMS-100", "MRZ", "chase"]
`

**Comment by LukePrior** [comment]
This is now live.

**Comment by rs1729** [comment]
Sorry, probably I missed something, but where is this drop down box?
On v2.sondehub.org I see the "Sonde Serial" search box, nothing dropping down.
A filter drop down box would be good, or maybe drop down check boxes such that e.g. "RS41", "RS41-SG", "RS41-SGP" could be combined.

Is it possible to not display chase cars?

**Comment by LukePrior** [comment]
Sorry it might not be clear this uses the sonde serial search box. You can just enter RS41 and click search which will only return RS41.

It is currently not possible to hide chase cars
