### ISSUE TITLE
Single-Sonde Query Issues

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-tracker#7]
Entering a serial number in the query button and hitting submit often does.. nothing.

Reloading the page with the query added to the URL (e.g. appending `&q=8136843`) works, so the query aspect *is* working, but the submit isn't.

**Comment by LukePrior** [comment]
This has now been fixed on the testing branch.

**Comment by LukePrior** [comment]
This is working correctly now.
