### ISSUE TITLE
RS display problem

### ISSUE THREAD

**Issue by 14ri004** [projecthorus/sondehub-tracker#77]
hello, I have been using Sondehub for almost 3 years, but for about 8 days we have noticed a very big slowdown in the display of the RS and this on 3 PCs, 1 Tablet, and 1 Phone, it becomes very difficult to be able to follow a probe, and we are 5 people to have the same problem, the BETA version works perfectly well before, well done and thank you for your work

**Comment by TheSkorm** [comment]
Thanks for the report @14ri004 . We are looking into options to resolve this, it seems to be regression from when we switched to websockets. Do you happen to know if this is a CPU, Memory or Network limitation?

**Comment by 14ri004** [comment]
hello, we've been doing it for about 8 days, it's lagging, very slow screen display, see blocked, the processor is running at maximum, with the BETA version everything was perfect, I use Intel Core 2 duo 2.0Ghz and 2.8Ghz, friends use I5 and I7 and the problem is the same, before the probe appears on the Sondehub screen, it happens 5 to see 10mn and whatever the internet connection and the PC used, I hope you find the solution, and thank you for your help.

**Comment by TheSkorm** [comment]
Thanks for the information @14ri004 . as a work around, if you know the serial number for the radiosonde you can filter the website to just that serial, eg : https://sondehub.org/#!q=T0440081

**Comment by 14ri004** [comment]
The problem is that we cannot get the number, the probe is not visible on SondeHub, otherwise yes I know the manipulation, as long as there are not many websock messages, c  'is OK, but from 200/300 finished no longer possible to display the new probes, today after 1h30 and multiple restart of SondeHub, the probes that I wanted to follow were still invisible.

**Comment by TheSkorm** [comment]
Hi @14ri004 I just pushed some changes to our testing branch that might help you out. Can you check https://testing.v2.sondehub.org when the next radiosonde is released and report back if this resolves your issue?

**Comment by 14ri004** [comment]
hello, yes ok we will do the tests and I will come back to you to inform you of the result, thank you

**Comment by 14ri004** [comment]
perfect, we tested the test probehub with 4 people? and the detection as well as the navigation in the page was very good, no more slowing down like yesterday, thank you

**Comment by TheSkorm** [comment]
Thanks for the feedback :)
