### ISSUE TITLE
Radiosonde Launch Site - Locations

### ISSUE THREAD

**Issue by LukePrior** [projecthorus/sondehub-tracker#81]
We source our list of Radiosonde launch sites from [rs1729](https://github.com/rs1729/RS/issues/15) who gets his data from [Ogimet](https://www.ogimet.com/home.phtml.en). This data is not perfect and several stations do are not included in the list or information regarding what Radiosondes they launch is limited.

You can report an incorrect or missing station by creating a comment in this issue with the following details:

Station number:  (e.g. 68263)
Radiosonde Types Launched: (e.g. 84)
Latitude: (e.g. -25.91, please limit to 6 decimal places)
Longitude: (e.g. 28.21, please limit to 6 decimal places)
Altitude: (e.g. 1526)
Station name: (e.g. Pretoria Irene (South Africa))

**Comment by 14ri004** [comment]
Guipavas station not in the right place

Sondes M10
48.444548616162606
-4.4124001735581455
95m
Guipavas (France)

**Comment by 14ri004** [comment]
Trappes station not in the right place

Sondes M10
48.77309665771168
2.0093766687839496
170m
Trappes (France)

**Comment by 14ri004** [comment]
Camborne station not in the right place

Sondes RS41
50.218697669926534
-5.326913972212803
85m
Camborne (Angleterre)

**Comment by 14ri004** [comment]
Herstmonceux station not in the right place

Sondes RS41
50.89130626202489
0.31752074725649077
55m
Herstmonceux (Angleterre)

**Comment by darksidelemm** [comment]
OK, I think we need to reign this back in a bit. We are using data provided by WMO which has limited precision. If the site is within a few km then that's sufficient.

Also please try and lump together your suggestions so I don't get heaps of notification emails...

**Comment by LukePrior** [comment]
Ok so new plan as RS1729 notes the igra2 station list has higher precision (4 decimal places) which should get us within a few metres. I will see if I can write some quick code to merge the two datasets together by station number.

**Comment by LukePrior** [comment]
Ok I have updated [launchSites.json](https://github.com/projecthorus/sondehub-tracker/blob/master/launchSites.json) with the igra2 data and your data @14ri004.

**Comment by TheSkorm** [comment]
Melbourne BoM Training Annex (Training and Ozonesondes)
RS41
-37.689883329756526, 144.9473753844475

**Comment by 14ri004** [comment]
M10
44.831398421186776 
-0.6919924361902385
50m
Bordeaux (France)

M20
43.85657578249786
4.405732359934679
60m
Nimes (France)

M10
41.91780784232488
8.793268764528202
2m
Ajaccio (France)

**Comment by 14ri004** [comment]
Nîmes (FRANCE) sonde M20

**Comment by 14ri004** [comment]
center of Ury (77 France) 48.337861N, 2.60012E
manufacturer METEOMODEM
loose M10 and M20 probes

**Comment by LukePrior** [comment]
> center of Ury (77 France) 48.337861N, 2.60012E
> manufacturer METEOMODEM
> loose M10 and M20 probes

Please only post in one issue

**Comment by 14ri004** [comment]
hello, sorry, there are two topics, which one to choose ??

**Comment by LukePrior** [comment]
Please use the other issue for all station adjustments and additions in future.
