### ISSUE TITLE
Perdicted Path Display of Old Sondes

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-tracker#9]
Hi,

It seems that the V2 website display stops showing the predicted path of old ones earlier than V1/HabHub.
I'm attaching a screenshot showing the same ~6 hours old sonde in both HabHub (on the right) and in SondeHub (no predicted path) . At times, that predicted path is quite useful.

What is the time limit? Is really shorter than in V1? Can it be extended?

Thanks.

![image](https://user-images.githubusercontent.com/43761289/116658430-9b444d80-a998-11eb-8e11-7d30f2f95c69.png)

**Comment by ZigiWalter** [comment]
@darksidelemm @TheSkorm, I've realized that I'm not sure you get notifications about issues in the repository...
Sorry for the spam, if you do.

Thanks.

**Comment by darksidelemm** [comment]
Yes, it's much shorter, it'll only run predictions for sondes that have had data in the last 15 minutes. I'm not sure what's involved to extend this - that's a @TheSkorm  question...

**Comment by LukePrior** [comment]
Yeah I've noticed the same thing we were talking about it on the Discord. It would be handy to always get predictions.

**Comment by TheSkorm** [comment]
This can certainly be resolved, but it need a bit of thinking about how to perform it without overwhelming elasticsearch. Probably will be awhile before I have a look. The easy midterm solution might be to always run predictions on sondes when filtered

**Comment by LukePrior** [comment]
> The easy midterm solution might be to always run predictions on sondes when filtered

This sounds like a good fix.

**Comment by TheSkorm** [comment]
@LukePrior thinking about this more, since we do run our own predictor maybe we could handle this from the frontend and call our predictor directly ? The reason we were calling it through our API was to format the data to be backwards compatible to habhub since we were only doing minimal tracker changes.

**Comment by TheSkorm** [comment]
wait, nevermind, I remember why we can't do this, the wind model gets out of date for old sondes!

**Comment by LukePrior** [comment]
> wait, nevermind, I remember why we can't do this, the wind model gets out of date for old sondes!

So is the only way we can do this is with caching in elastic search or something?

**Comment by ZigiWalter** [comment]
In case there's no simple solution - what about storing just the predicted landing spot (not the path), as part of the other sonde data (freq, type, altitude) in SonderHub DB...?

**Comment by TheSkorm** [comment]
I'll have a look at what we can do next time I keep some free time :)

**Comment by TheSkorm** [comment]
This should be resolved now :)

**Comment by ZigiWalter** [comment]
This is great, thanks!
